<?php
// $Id$

// lis_gbrowse

// Sudhansu Dash
// 2016 April 22


/**
 * Implements hook_menu().
 */

function lis_gbrowse_menu() {
  $items = array();
  $items['genomes/gbrowse/%'] = array( //this creates a URL with wildcard for the species specific gbrowse path
    'title' => 'GBrowse', //page title
    'description' => 'GBrowse at LIS.',
    'page callback' => lis_gbrowse_page_callback, //this fn is called when page accessed. For form, use drupal_get_form
    //'page arguments' => array('grin_acc_query_form'), //form name here; no need if page callback fn() doesn't need it.
    'page arguments' => array(2), // the args for page callback function '2' is the 3rd component of path (0 based index);
    'access callback' => TRUE,
  );
  
  return $items;
}


/**
 * Implements hook_theme().
 */


function lis_gbrowse_theme() {
  return array(
    'lis_gbrowse_page_template' => array(  // this array name to be used in theme() fn.
    'template' => 'lis_gbrowse_page',  //template file lis_gbrowse_page.tpl.php
    //'variables' => array(),
    ),  //array page_template
  );  // array return
}    

/**
 * Implements page callback.
 */
function lis_gbrowse_page_callback($third_path_component) {
  
  //echo '---'.$bb.'---';
  //$path = $_GET['q'];
  //echo 'path: '.$path;
  
  ##Query params for gbrowse utility
  $qry_params = $_GET['query'];   # 'q' fails because drupal uses 'q' internally
  $qry_params = "/?".$qry_params;
  
  $url_source = "/gb2/gbrowse/$third_path_component";
  $url_source = $url_source.$qry_params;   
  
   
  // array name in hook_theme() that specifies page template file.
  return theme ('lis_gbrowse_page_template', array('url_source' => $url_source)); 
}




//  SCRATCH PAD
//=============

/*
 

*/
